# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_user', models.CharField(max_length=50, verbose_name='')),
                ('com_mail', models.EmailField(max_length=254)),
                ('com_data', models.TextField()),
            ],
            options={
                'db_table': 'comm',
            },
        ),
        migrations.CreateModel(
            name='Dictonary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('mean', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'dictonary',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4)),
                ('full_name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'lang',
            },
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('post_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Lang')),
            ],
            options={
                'db_table': 'post_data',
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'post_type',
            },
        ),
        migrations.AddField(
            model_name='postdata',
            name='post_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.PostType'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='connects',
            field=models.ManyToManyField(to='kernel.PostData'),
        ),
        migrations.AddField(
            model_name='dictonary',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.Lang'),
        ),
        migrations.AddField(
            model_name='comment',
            name='com_arnold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.PostData'),
        ),
    ]
